#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : beniget
Version  : 0.3.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/50/b9/7d864a50d5d2821686d4374400de45c8e0678e553657343f5f0ea6aff98d/beniget-0.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/50/b9/7d864a50d5d2821686d4374400de45c8e0678e553657343f5f0ea6aff98d/beniget-0.3.0.tar.gz
Summary  : Extract semantic information about static Python code
Group    : Development/Tools
License  : BSD-3-Clause
Requires: beniget-python = %{version}-%{release}
Requires: beniget-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : gast-python
BuildRequires : pip

%description
A static analyzer for Python2 and Python3 code.
        
        Beniget provides a static over-approximation of the global and
        local definitions inside Python Module/Class/Function.
        It can also compute def-use chains from each definition.

%package python
Summary: python components for the beniget package.
Group: Default
Requires: beniget-python3 = %{version}-%{release}

%description python
python components for the beniget package.


%package python3
Summary: python3 components for the beniget package.
Group: Default
Requires: python3-core
Provides: pypi(beniget)
Requires: pypi(gast)

%description python3
python3 components for the beniget package.


%prep
%setup -q -n beniget-0.3.0
cd %{_builddir}/beniget-0.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1624295635
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
